### ISSUE TITLE
Dependency on EBimage makes install impossible on MacOS and hard on Ubuntu

### ISSUE THREAD

**Issue by aourednik** [ZenBrayn/r-turing-patterns#1]
Very nice package! The installation command fails, though, due to EBimage dependency.
On Ubuntu, you need to install in the following order:
- install shiny from CRAN and its dependencies
- sudo apt install libtiff5  libtiff5-dev
- sudo apt install fftw3 libfftw3-bin libfftw3-dev
- from R: BiocManager::install("EBImage")
- only then you can run `remotes::install_github("ZenBrayn/r-turing-patterns", dependencies = TRUE)`

On MacOS, this fails, as EBimage depends on the tiff package that is not available as a binary and whose compilation depends not only on libtiff - installable via Homebrew - but also on libtiff-dev, apparently only available for Linux. The fftw dependency has the same problem.

Perhaps the EBimage dependency could be replaced by a more user-friendly image library like magick (https://cran.r-project.org/web/packages/magick/index.html) ?

**Comment by ZenBrayn** [comment]
(a little late to respond here…)
Thanks for the report!  I’m on a Mac actually, so I got it to work at some point, but don’t recall why I decided to use EBImage.  I don’t see any reason why I couldn’t use something else.  I’ll give it a shot and report back (no ETA though).

**Comment by ZenBrayn** [comment]
I tried a few different options, but didn't get anything I liked

- magick image_blur function: the image functions work on an image object that must be read from an image file, not a numeric matrix which we have here.  
- spatstats blur function: seems to have worked but it's much slower compared to EBImage

So... sticking with EBImage for now.  Very odd that you were unable to install this on a Mac since that's my main platform and I didn't run into any issues.  But, I know package installs can easily go frustratingly sideways.
