### ISSUE TITLE
Error when grid less than 201

### ISSUE THREAD

**Issue by royfrancis** [ZenBrayn/r-turing-patterns#2]
```
> turingpatterns::turing_pattern(100,100,10)

Error: Problem with `mutate()` column `activator_mtrx`.
ℹ `activator_mtrx = purrr::map2(...)`.
x 'filter' dimensions cannot exceed dimensions of 'x'
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by ZenBrayn** [comment]
Thanks for the issue @royfrancis.  This error is due to the supplied radius parameters which must be smaller than the grid x and y dimensions.  In the case of the default parameters, one of the inhib_radius values is 200 so grid x and y must be > 200, or the radius values need to be < 200.

I've updated the function to check and throw an error if these conditions are not met.
